# a_tensor_initialization.py

In [1]:
import torch
import numpy as np

In [2]:
t1 = torch.Tensor([1,2,3], device ='cpu')
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)

t1_cpu = t1.cpu()
print("#"*50, 1)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1


In [3]:
t2 = torch.tensor([1,2,3], device='cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

t2_cpu = t2.cpu()
print("#"*50, 2)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2


In [4]:
a1 = torch.tensor(1)			           # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	       # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2


In [5]:
a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5


In [6]:
a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

torch.Size([4, 1, 5]) 3


ValueError: ignored

# b tensor_initialization_copy.py

In [7]:
# Python list나 Numpy 배열을 PyTorch 텐서로 변환하는 방법
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)        # 텐서인 경우, 기존 텐서 그대로 반환 (이 경우 그대로 반환하고 있음)


l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)           # 입력 데이터 복사하여 새로운 텐서 만들기에 변경되지 X
print(t2)           # 입력 데이터 복사하여 새로운 텐서 만들기에 변경되지 X
print(t3)           # 텐서인 경우, 기존 텐서를 그대로 반환하기에 변경되지 X

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [8]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100           # 배열이기에 텐서가 아님, 기존 텐서를 그대로 반환하지 않아 값이 100으로 바뀌는 것을 볼 수 있음

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


# c_tensor_initialization_constant_values.py

In [9]:
t1 = torch.ones(size=(5,))
t1_like = torch.ones_like(input=t1) # 입력 텐서와 같은 크기와 타입을 갖는 텐서를 생성하고, 모든 요소를 1로 채운다.
print(t1)
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [10]:
t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2)  # 입력 텐서와 같은 크기와 타입을 갖는 텐서를 생성하고, 모든 요소를 0으로 채운다.
print(t2)
print(t2_like)

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [11]:
t3 = torch.empty(size=(4,)) # 주어진 크기의 아무값으로 초기화 되지 않은 텐서를 생성한다.
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like)

tensor([1.8682e+12, 4.3554e-41, 1.8682e+12, 4.3554e-41])
tensor([4.2490e-05, 8.3026e-10, 2.1707e-18, 4.5447e+30])


In [12]:
t4 = torch.eye(n=3) # 대각이 1이고 나머지가 0인 행렬 생성, 대각행렬이다.
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# d_tensor_initialization_random_values.py

In [13]:
t1 = torch.randint(low=10, high=20, size=(1, 2))          # 10부터 20까지의 정수 중에서 임의로 선택된 2개의 값을 갖는 사이즈가 (1,2)인 텐서를 생성
print(t1)

t2 = torch.rand(size=(1, 3))                             # 0과 1 사이의 실수를 갖는 사이즈가 (1,3)인 텐서를 생성
print(t2)

t3 = torch.randn(size=(1, 3))                            # 표준 정규 분포에서 랜덤한 실수를 갖는 사이즈가 (1,3)인 텐서를 생성
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))       # 평균이 10이고 표준 편차가 1인 정규 분포에서 랜덤한 실수를 갖는 사이즈가 (3,2)인 텐서를 생성
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)         # start(0)와 end(5) 사이에서 steps(3) 개수만큼 균등하게 분포된 텐서를 생성
print(t5)

t6 = torch.arange(5)                                     # 0부터 end(5) 이전까지의 개수만큼의 텐서를 생성
print(t6)

tensor([[14, 14]])
tensor([[0.4444, 0.4753, 0.1751]])
tensor([[-0.9641,  0.1780, -0.3960]])
tensor([[ 8.3381, 11.4319],
        [11.5396,  9.3473],
        [10.6309,  9.5243]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


In [14]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)                               # random1은 torch.manual_seed(1729) 함수를 호출한 후에 생성된 난수값으로 텐서를 형성한다.
print(random1)

random2 = torch.rand(2, 3)                               # random2는 torch.manual_seed(1729) 함수를 호출한 후에 생성된 난수값으로 텐서를 형성한다.
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)                               # random3은 torch.manual_seed(1729) 함수가 다시 한번 호출된 뒤에 난수값을 생성하였기에 random1과 동일한 난수값으로 텐서가 형성한다.
print(random3)

random4 = torch.rand(2, 3)                               # random4는 torch.manual_seed(1729) 함수가 다시 한번 호출된 뒤에 난수값을 생성하였기에 random2과 동일한 난수값으로 텐서가 형성한다.
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion.py

In [15]:
a = torch.ones((2, 3))
print(a.dtype)      #텐서의 데이터 타입 (32비트 부동 소수점 타입)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)            #모든 요소가 1로 채워진 사이즈 (2,3)의 텐서 생성 (16비트 정수 타입)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)            #0과 1사이의 실수를 갖는 사이즈 (2,3)의 텐서에 20을 곱하여 생성 (64비트 실수 타입)

d = b.to(torch.int32)
print(d)            # (2,3) 사이즈의 텐서를 생성하고, 모든 원소를 32비트 정수로 변환한 후에 출력

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [16]:
#텐서의 데이터타입 변환
double_d = torch.ones(10, 2, dtype=torch.double)              # 64비트 부동 소수점 텐서를 생성 (사이즈:(10,2))
short_e = torch.tensor([[1, 2]], dtype=torch.short)           # 16비트 정수 텐서를 생성 (사이즈:(1,2))

double_d = torch.zeros(10, 2).double()                        # 64비트 부동 소수점 텐서를 생성하고, double 메서드를 사용하여 데이터 타입을 64비트 부동 소수점으로 변환
short_e = torch.ones(10, 2).short()                           # 16비트 정수 텐서를 생성하고, short 메서드를 사용하여 데이터 타입을 16비트 정수로 변환

double_d = torch.zeros(10, 2).to(torch.double)                # to() 메서드를 사용하여 데이터 타입을 64비트 부동 소수점으로 변환
short_e = torch.ones(10, 2).to(dtype=torch.short)             # to() 메서드를 사용하여 데이터 타입을 16비트 정로 변환

double_d = torch.zeros(10, 2).type(torch.double)              # type() 메서드를 사용하여 데이터 타입을 64비트 부동 소수점으로 변환
short_e = torch.ones(10, 2). type(dtype=torch.short)          # type() 메서드를 사용하여 데이터 타입을 16비트 정수로 변환

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)                             # 두 텐서의 데이터 타입이 다르기 때문에 PyTorch가 두 텐서의 데이터 타입을 공통 분모로 변환

torch.float64
torch.int16
torch.float64


# f_tensor_operations.py

In [17]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)       #텐서 더하기(add의 경우, 데이터 타입이 다를 때도 덧셈 가능하다)
t4 = t1 + t2                 #텐서 더하기
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [18]:
t5 = torch.sub(t1, t2)       #텐서 빼기 (데이터 타입이나 크기가 달라도 뺄셈 가능)
t6 = t1 - t2                 #텐서 빼기
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [19]:
t7 = torch.mul(t1, t2)       #텐서 곱하기 (데이터 타입이나 크기가 달라도 곱셈 가능)
t8 = t1 * t2                 #텐서 곱하기
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [20]:
t9 = torch.div(t1, t2)       #텐서 나누기 (데이터 타입이나 크기가 달라도 나눗셈 가능)
t10 = t1 / t2                #텐서 나누기
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_mm.py


In [21]:
import torch

t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())           #백터의 내적 계산 (t1 = 2 * 2 + 3 * 1=7)

t2 = torch.randn(2, 3)         # 사이즈가 (2,3)인 평균이 0이고 표준편차가 1인 정규 분포에서 값 무작위로 초기화
t3 = torch.randn(3, 2)         # 사이즈가 (3,2)인 평균이 0이고 표준편차가 1인 정규 분포에서 값 무작위로 초기화
t4 = torch.mm(t2, t3)          # 텐서의 행렬 곱셉 실행
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)     # 10개의 배치가 있고, 각 배치마다 (3,4) 사이즈의 행렬포함
t6 = torch.randn(10, 4, 5)     # 10개의 배치가 있고, 각 배치마다 (4,5) 사이즈의 행렬포함
t7 = torch.bmm(t5, t6)         # 배치 매트릭스 곱셈 수행
print(t7.size())               # 행렬 곱셈 수행하기에 결과와 텐서도 같은 배치 유지됨

tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


#h_tensor_operations_matmul.py

In [22]:
# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())       # 둘 다 1차원 텐서이기에 내적 수행했을때, 스칼라값을 반환한다.
                                         # 스칼라는 차원이 없기에 torch.Size([])가 출력된다.

torch.Size([])


In [24]:
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())       # 행렬 * 벡터의 값을 수행한다. 행렬 곱셈을 수행했을 때, t3의 행은 t4와 내적되어 스칼라값 반환한다.
                                         # 그렇기에 크기가 3인 1차원 벡터인 torch.Size([3])이 출력된다.

torch.Size([3])


In [23]:
# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())       # 배치된 행렬 * 벡터의 값을 수행한다. 행렬 곱셈을 수행했을 때, t5의 배치은 t6와 내적되어 [10,3]을 반환한다.
                                         # 그렇기에 크기가 (10,3)인 2차원 벡터인 torch.Size([10,3])이 출력된다.

torch.Size([10, 3])


In [25]:
# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())       # 배치된 행렬 * 배치된 행렬 값을 수행한다. 배치 매트릭스 곱셈을 수행했을 때,[10,3,5]를 반환한다.
                                         # 그렇기에 크기가 (10,3,5)인 3차원 벡터인 torch.Size([10,3,5])가 출력된다.

torch.Size([10, 3, 5])


In [26]:
# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())      # 배치된 행렬 * 행렬 값을 수행한다. 배치 매트릭스 곱셈을 수행했을 때,[10,3,5]를 반환한다.
                                         # 그렇기에 크기가 (10,3,5)인 3차원 벡터인 torch.Size([10,3,5])가 출력된다.

torch.Size([10, 3, 5])


# i_tensor_broadcasting.py

In [27]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)                    # 텐서 * 스칼라 곱셈 수행 (각 원소에 broadcasting 되어 원소와의 곱셈이 일어남)

tensor([2., 4., 6.])


In [28]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)                   # 행렬 - 벡터 뺄셈 수행 (broadcasting에 따라 벡터가 행렬의 각 행에 대해 빼기 연산 수행 )

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [29]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)   #행렬 t5 + 2.0
print(t5 - 2.0)  # t5.sub(2.0)   #행렬 t5 - 2.0
print(t5 * 2.0)  # t5.mul(2.0)   #행렬 t5 * 2.0
print(t5 / 2.0)  # t5.div(2.0)   #행렬 t5 / 2.0

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [30]:
def normalize(x):                 # 정규화 수행 [0,255] -> [0,1]
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())       # 정규화 된 텐서의 크기는 입력 텐서 t6와 동일 (텐서의 차원은 변경되지 X)

torch.Size([3, 28, 28])


In [31]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [32]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)              # t11에 t12를 곱하여 broadcasting 된 연산은 텐서가 (4,3,2)크기와 호환되도록 확장하여 크기가 (4,3,2)로 유지됨

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)              # t13에 t14를 곱하여 broadcasting 된 연산은 텐서가 (4,3,2)크기와 호환되도록 확장하여 크기가 (4,3,2)로 유지됨

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)              # t15에 t16를 곱하여 broadcasting 된 연산은 텐서가 (4,3,2)크기와 호환되도록 확장하여 크기가 (4,3,2)로 유지됨

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)     # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())     # t17에 t18를 곱하여 broadcasting 된 연산은 텐서가 (5,3,4,1)크기와 호환되도록 확장하여 크기가 (5,3,4,1)로 유지됨

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


In [33]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())    # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


In [34]:
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)   #제곱연산
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


# j_tensor_indexing_slicing.py

In [35]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9]) ([1]의 행)
print(x[:, 1])  # >>> tensor([1, 6, 11])   (행은 무한대, [1]의 열)
print(x[1, 2])  # >>> tensor(7)            ([1]의 행, [2]의 열)
print(x[:, -1])  # >>> tensor([4, 9, 14)   (행은 무한대, [-1]의 열)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [36]:
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]]) ([1] 이상의 행)
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]]) ([1]이상의 행 & [3] 이상의 행)

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [37]:
y = torch.zeros((6, 6))   # 사이즈가 (6,6)이고 0으로 구성됨
y[1:4, 2] = 1             # 행은 [1-3], 열은 [2]에 포함되는 곳을 1로 변경
print(y)

print(y[1:4, 1:4])

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [38]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])       #[2] 미만의 행
print(z[1:, 1:3])  #[1] 이상의 행 & [1-2]의 열
print(z[:, 1:])    # [1] 이상의 열

z[1:, 1:3] = 0     # [1]이상의 행 & [1-2]의 열에 0 넣기
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping.py

In [39]:
# 텐서의 모양 변경
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)  (요소를 모양에 맞추어 배열, 요소 순서변경은 X)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [40]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,) (차원 중 1인 것을 제거하여 생성됨)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1) (첫번째 차원 제거)
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [41]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1) (텐서의 차원 확장)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3) (텐서의 차원 확장(기존 텐서의 두 번째 차원(인덱스1) 앞에 새로운 차원 추가))
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [42]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,) (1차원으로 flatten 시킴)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)     # t15 flatten (1차원으로 flatten 됨)

t17 = torch.flatten(t15, start_dim=1)    # [1] 이후를 flatten 시킴

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [43]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> 차원의 순서를 (2,0,1) 순으로 변경하기에 torch.Size([5, 2, 3])됨

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3)
t21 = torch.permute(t19, dims=(1, 0))  # 차원을 (1,0)으로 변경하기에 shape은 (3, 2)가 된다
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # 차원 0,1을 사용하여 전치하기에 차원이 서로 바뀌어 shape은 (3, 2)가 된다

print(t22)

t23 = torch.t(t19)  # torch.t 함수를 이용해 차원을 전치시키기에 shape은 (3, 2)가 된다

print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_contact.py

In [44]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)        # 첫번째 차원을 연결 => 1+3+2 = 6
print(t4.shape)

torch.Size([2, 6, 3])


In [45]:
t5 = torch.arange(0, 3)  # (0부터 2까지) tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # (3부터 7까지) tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim= 0)
print(t7.shape)  # ([0,1,2,3,4,5,6,7]) torch.Size([8])
print(t7)  #  tensor([0, 1, 2, 3, 4, 5, 6, 7])

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [46]:
t8 = torch.arange(0, 6).reshape(2, 3)   # 0에서 5까지 Size는 ([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # 6에서 11까지 Size는 ([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)        # 행방향을 기준으로 병합
print(t10.size())                       # torch.Size([4, 3])
print(t10)

t11 = torch.cat((t8, t9), dim=1)        # 열방향을 기준으로 병합
print(t11.size())                       # torch.Size([2, 6])
print(t11)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [47]:
t12 = torch.arange(0, 6).reshape(2, 3)    # Size는 ([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)   # Size는 ([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # Size는 ([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)   # 행방향을 기준으로
print(t15.size())                         # Size는 ([6, 3])
print(t15)


t16 = torch.cat((t12, t13, t14), dim=1)   # 열방향을 기준으로
print(t16.size())                         # Size는 ([2, 9])
print(t16)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [48]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)   # 0부터 5까지 Size는 ([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # 6부터 11까지 Size는 ([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)          # 행방향을 기준으로
print(t19.size())                           # Size는 ([2, 2, 3])
print(t19)

t20 = torch.cat((t17, t18), dim=1)          # 열방향을 기준으로
print(t20.size())                           # Size는 ([1, 4, 3])
print(t20)


t21 = torch.cat((t17, t18), dim=2)          # 3번째 차원을 기준으로
print(t21.size())                           # Size는 ([1, 2, 6])
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking.py

In [49]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)  # 행방향을 기준으로 텐서 생성
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)   #t1과 t2를 첫번째 차원에서 확장한 후 행방향을 기준으로 텐서 생성함
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)  # 열방향을 기준으로 텐서 생성
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)   #t1과 t2를 두번째 차원에서 확장한 후 열방향을 기준으로 텐서 생성함
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)  # 3번째 차원을 기준으로 텐서 생성
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)   #t1과 t2를 세번째 차원에서 확장한 후 3번째 차원을 기준으로 텐서 생성함
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [50]:
t9 = torch.arange(0, 3)       # tensor([0, 1, 2])
t10 = torch.arange(3, 6)      # tensor([3, 4, 5])

print(t9.size(), t10.size())  # t9의 Size는 ([3]), t1의 Size는 ([3])

t11 = torch.stack((t9, t10), dim=0)  # 행방향을 기준으로 텐서 생성
print(t11.size())                    # Size는 ([2,3])
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)   #t9과 t10을 첫번째 차원에서 확장한 후 행방향을 기준으로 텐서 생성함
print(t11.equal(t12))

t13 = torch.stack((t9, t10), dim=1)  # 열방향을 기준으로 텐서 생성
print(t13.size())                    # Size는 ([3,2])
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)   #t9과 t10을 두번째 차원에서 확장한 후 열방향을 기준으로 텐서 생성함
print(t13.equal(t14))

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


#n_tensor_vstack_hstack.py

In [51]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))         # t1과 t2를 수직으로 쌓아서 새로운 2차원 텐서 생성
print(t3)

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))         # t4과 t5를 수직으로 쌓아서 새로운 2차원 텐서 생성


t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)                     # shape는 (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)                     # shape는 (2, 2, 3)

t9 = torch.vstack([t7, t8])         # t7과 t8를 수직으로 쌓아서 새로운 3차원 텐서 생성
print(t9.shape)                     # shape는 (4, 2, 3)

print(t9)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [52]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))      # t10과 t11을 수평으로 결합해서 새로운 텐서 생성
print(t12)

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))      # t13과 t14를 수평으로 결합해서 새로운 텐서 생성
print(t15)

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)                     # shape는 (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)                     # shape는 (2, 2, 3)


t18 = torch.hstack([t16, t17])       # t16과 t17을 수평으로 결합해서 새로운 3차원 텐서 생성
print(t18.shape)                     # shape는 (2, 4, 3)

print(t18)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


<고찰>
이번 과제를 통해 솔직히 개념적으로만 이해했고 헷갈렸던 텐서의 개념과 텐서와 데이터타입, 요소들의 개념에 대해 확실히 이해할 수 있었다.
이 과제는 텐서를 만들고 결합하고, 나누고, 확장하고, 제거하는 등의 학습을 통해 텐서가 어떻게 달라지는지를 관찰하고, 이해하면서 한결 더 나은 개념이 잡혔다고 생각한다.

<숙제후기>
컴퓨터에 pycharm, git, anaconda를 깔면서, 솔직히 지금도 환경 조성이 안되어서 급하게 노트북을 빌려 과제를 해결하였다.
처음 pytorch를 까는 과정에서 오류가 한번 생기니, pytorch를 지웠다가 다시 깔아도 애초에 pytorch에서 에러가 생겼다.
직접 나의 노트북으로 이번 과제를 해결하고 싶었지만, 이번 과제는 불가능하다고 판단해 다음 과제부터는 나의 노트북으로 해결할 수 있도록, 한번 더 시도해보아야 겠다.